from fastapi import FastAPI
from pydantic import BaseModel
from typing import List, Union
from services.gemini import get_gemini_response
from fastapi.middleware.cors import CORSMiddleware

# App initialization

app = FastAPI(
    title="Recipe and Meal Planning API",
    description="API for generating recipes and meal plans using Gemini AI",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# Pydantic models for request and response


class QueryRequest(BaseModel):
    """
    Pydantic model for getting the user query
    """
    
    query: str


class Details(BaseModel):
    """
    Pydantic model for detailed recipe response
    """
    
    recipe_name: str
    ingredients: List[str]
    instructions: List[str]
    tips: List[str]
    prep_time: str


class RecipeResponse(BaseModel):
    """
    Pydantic model for recipe response
    """
    
    answer: str
    details: Details


class ErrorResponse(BaseModel):
    """
    Pydantic model for error response
    """

    error: str
    status_code: int


@app.get("/")
async def read_root():
    """
    Root endpoint for health check.
    """

    return {"message": "Recipe and Meal Planning API is running"}


@app.post("/api/query", response_model=Union[RecipeResponse, ErrorResponse])
async def query_recipe(request: QueryRequest):
    """
    Process a user query and return a recipe generated by Gemini AI.

    Args:
        request: QueryRequest object containing the user's query.

    Returns:
        RecipeResponse with the recipe details.

    Raises:
        HTTPException: If the query is invalid or Gemini AI fails.
    """

    if not request.query.strip():
        return ErrorResponse(error="Query cannot be empty", status_code=400)

    try:
        response = get_gemini_response(request.query)

        return RecipeResponse(**response)

    except Exception as e:
        return ErrorResponse(error=f"Error processing query: {str(e)}", status_code=500)
